import aiohttp
from typing import Dict, Any, Optional

class WebhookDispatchService:
    """
    Formats and dispatches AssemblyAI LeMUR Executive Briefings to Telegram, Slack,
    and custom webhook integrations.
    """

    async def dispatch_briefing(
        self,
        briefing: Dict[str, Any],
        destination: str, # "telegram" | "slack" | "custom"
        target_url_or_token: str,
        chat_id: Optional[str] = None
    ) -> Dict[str, Any]:
        """Dispatches structured briefing to the chosen destination."""
        if not target_url_or_token:
            return {"success": False, "error": "Target URL or Bot Token is required."}

        dest_lower = destination.lower()

        if "telegram" in dest_lower:
            return await self._send_telegram(briefing, target_url_or_token, chat_id or "")
        elif "slack" in dest_lower:
            return await self._send_slack(briefing, target_url_or_token)
        else:
            return await self._send_custom_webhook(briefing, target_url_or_token)

    async def _send_telegram(self, briefing: Dict[str, Any], bot_token: str, chat_id: str) -> Dict[str, Any]:
        """Sends clean formatted Markdown message to Telegram chat."""
        if not chat_id:
            return {"success": False, "error": "Telegram Chat ID is required."}

        title = briefing.get("title", "Sonar AI Research Briefing")
        consensus = briefing.get("consensus_score", "Neutral")
        summary = briefing.get("executive_summary", "")
        takeaways = briefing.get("key_takeaways", [])
        citations = briefing.get("verified_citations", [])

        takeaways_text = "\n".join([f"• {t}" for t in takeaways[:3]])
        citations_text = "\n".join([f"• [{c.get('platform')}] {c.get('author_or_source')}: {c.get('url')}" for c in citations[:3]])

        message_text = (
            f"🌊 *{title}*\n"
            f"📊 *Consensus:* `{consensus}`\n\n"
            f"🎯 *Executive Summary:*\n{summary}\n\n"
            f"💡 *Key Takeaways:*\n{takeaways_text}\n\n"
            f"🔗 *Sources:*\n{citations_text}\n\n"
            f"_Generated by Sonar AI with AssemblyAI LeMUR_"
        )

        url = f"https://api.telegram.org/bot{bot_token}/sendMessage"
        payload = {
            "chat_id": chat_id,
            "text": message_text,
            "parse_mode": "Markdown"
        }

        try:
            async with aiohttp.ClientSession() as session:
                async with session.post(url, json=payload, timeout=10) as resp:
                    if resp.status == 200:
                        return {"success": True, "destination": "telegram", "status": "Delivered"}
                    else:
                        err_text = await resp.text()
                        return {"success": False, "error": f"Telegram API error ({resp.status}): {err_text}"}
        except Exception as e:
            return {"success": False, "error": f"Network error sending to Telegram: {str(e)}"}

    async def _send_slack(self, briefing: Dict[str, Any], webhook_url: str) -> Dict[str, Any]:
        """Sends rich Slack Block Kit message to incoming webhook."""
        title = briefing.get("title", "Sonar AI Research Briefing")
        consensus = briefing.get("consensus_score", "Neutral")
        summary = briefing.get("executive_summary", "")
        takeaways = briefing.get("key_takeaways", [])

        takeaways_text = "\n".join([f"• {t}" for t in takeaways[:3]])

        slack_blocks = {
            "blocks": [
                {
                    "type": "header",
                    "text": {
                        "type": "plain_text",
                        "text": f"🌊 {title}",
                        "emoji": True
                    }
                },
                {
                    "type": "section",
                    "fields": [
                        {"type": "mrkdwn", "text": f"*Consensus Rating:*\n`{consensus}`"},
                        {"type": "mrkdwn", "text": "*Source Engine:*\nAssemblyAI LeMUR"}
                    ]
                },
                {
                    "type": "divider"
                },
                {
                    "type": "section",
                    "text": {
                        "type": "mrkdwn",
                        "text": f"*Executive Summary:*\n{summary}"
                    }
                },
                {
                    "type": "section",
                    "text": {
                        "type": "mrkdwn",
                        "text": f"*Key Takeaways:*\n{takeaways_text}"
                    }
                }
            ]
        }

        try:
            async with aiohttp.ClientSession() as session:
                async with session.post(webhook_url, json=slack_blocks, timeout=10) as resp:
                    if resp.status == 200 or resp.status == 204:
                        return {"success": True, "destination": "slack", "status": "Delivered"}
                    else:
                        err_text = await resp.text()
                        return {"success": False, "error": f"Slack API error ({resp.status}): {err_text}"}
        except Exception as e:
            return {"success": False, "error": f"Network error sending to Slack: {str(e)}"}

    async def _send_custom_webhook(self, briefing: Dict[str, Any], webhook_url: str) -> Dict[str, Any]:
        """Dispatches full JSON payload to generic webhook."""
        try:
            async with aiohttp.ClientSession() as session:
                async with session.post(webhook_url, json=briefing, timeout=10) as resp:
                    return {"success": resp.status < 400, "status_code": resp.status}
        except Exception as e:
            return {"success": False, "error": str(e)}
