"use client";

import React, { useState } from "react";
import { FileText, Download, X, CheckCircle2, ExternalLink, Sparkles, Printer, Send, MessageCircle, AlertCircle, Loader2 } from "lucide-react";
import { getPlatformBadgeStyle } from "@/lib/utils";

export interface CitationItem {
  platform: string;
  author_or_source: string;
  url: string;
  quote_or_claim: string;
}

export interface PlatformBreakdown {
  twitter?: string;
  reddit?: string;
  youtube?: string;
  web?: string;
}

export interface ExecutiveBriefing {
  session_id: string;
  title: string;
  generated_at: string;
  executive_summary: string;
  consensus_score: string;
  platform_breakdown: PlatformBreakdown;
  key_takeaways: string[];
  verified_citations: CitationItem[];
  recommended_next_steps: string[];
  full_transcript: string;
  session_duration_seconds: number;
}

interface BriefingModalProps {
  briefing: ExecutiveBriefing | null;
  isOpen: boolean;
  onClose: () => void;
}

export const BriefingModal: React.FC<BriefingModalProps> = ({
  briefing,
  isOpen,
  onClose
}) => {
  const [dispatchType, setDispatchType] = useState<"telegram" | "slack" | null>(null);
  const [telegramToken, setTelegramToken] = useState("");
  const [telegramChatId, setTelegramChatId] = useState("");
  const [slackWebhook, setSlackWebhook] = useState("");
  const [isDispatching, setIsDispatching] = useState(false);
  const [dispatchStatus, setDispatchStatus] = useState<string | null>(null);

  if (!isOpen || !briefing) return null;

  const handleDownloadMarkdown = () => {
    const mdContent = `
# 🌊 ${briefing.title}
*Generated by Sonar AI with AssemblyAI LeMUR on ${briefing.generated_at}*
*Session ID: ${briefing.session_id} | Consensus: ${briefing.consensus_score}*

---

## 🎯 Executive Summary
${briefing.executive_summary}

---

## 🌐 Cross-Platform Consensus Breakdown
* **🐦 Twitter/X:** ${briefing.platform_breakdown.twitter || "N/A"}
* **👽 Reddit:** ${briefing.platform_breakdown.reddit || "N/A"}
* **📺 YouTube:** ${briefing.platform_breakdown.youtube || "N/A"}
* **🌐 Web & News:** ${briefing.platform_breakdown.web || "N/A"}

---

## 💡 Key Takeaways
${briefing.key_takeaways.map(t => `- ${t}`).join("\n")}

---

## 🔗 Verified Citations & Direct Sources
${briefing.verified_citations.map(c => `- **[${c.platform}]** [${c.author_or_source}](${c.url}): "${c.quote_or_claim}"`).join("\n")}

---

## 🚀 Recommended Next Steps
${briefing.recommended_next_steps.map(s => `- ${s}`).join("\n")}
    `.trim();

    const dataStr = "data:text/markdown;charset=utf-8," + encodeURIComponent(mdContent);
    const downloadAnchor = document.createElement("a");
    downloadAnchor.setAttribute("href", dataStr);
    downloadAnchor.setAttribute("download", `Sonar_Briefing_${briefing.session_id}.md`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
  };

  const handlePrint = () => {
    window.print();
  };

  const handleDispatch = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!dispatchType) return;

    setIsDispatching(true);
    setDispatchStatus(null);

    const target = dispatchType === "telegram" ? telegramToken : slackWebhook;
    try {
      const res = await fetch("http://localhost:8000/api/v1/briefing/dispatch", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          destination: dispatchType,
          target_url_or_token: target,
          chat_id: dispatchType === "telegram" ? telegramChatId : null,
          briefing: briefing
        })
      });

      const data = await res.json();
      if (data.success) {
        setDispatchStatus(`Successfully delivered to ${dispatchType.toUpperCase()}!`);
        setTimeout(() => {
          setDispatchType(null);
          setDispatchStatus(null);
        }, 2000);
      } else {
        setDispatchStatus(`Dispatch error: ${data.error || "Failed"}`);
      }
    } catch (err: any) {
      setDispatchStatus(`Connection error: ${err.message}`);
    } finally {
      setIsDispatching(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-md p-4 overflow-y-auto">
      <div className="sonar-panel rounded-2xl max-w-3xl w-full border border-cyan-500/30 shadow-2xl p-6 relative my-8">
        
        {/* Close Button */}
        <button
          onClick={onClose}
          className="absolute top-5 right-5 p-2 rounded-xl bg-white/5 hover:bg-white/10 text-gray-400 hover:text-white transition-colors"
        >
          <X className="w-5 h-5" />
        </button>

        {/* Header */}
        <div className="border-b border-cyan-500/20 pb-5 mb-5">
          <div className="flex items-center gap-3 mb-2">
            <div className="p-2.5 rounded-xl bg-cyan-500/10 border border-cyan-500/30 text-cyan-400">
              <FileText className="w-6 h-6" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h2 className="text-lg font-bold text-white tracking-wide">
                  {briefing.title}
                </h2>
                <span className="text-[10px] font-mono bg-cyan-500/20 text-cyan-300 border border-cyan-500/30 px-2 py-0.5 rounded">
                  ASSEMBLYAI LeMUR VERIFIED
                </span>
              </div>
              <p className="text-xs text-gray-400 font-mono">
                SESSION ID: {briefing.session_id} | GENERATED: {briefing.generated_at}
              </p>
            </div>
          </div>
        </div>

        {/* Consensus Banner */}
        <div className="p-4 rounded-xl border border-cyan-500/30 bg-cyan-950/40 shadow-lg shadow-cyan-950/30 flex items-center justify-between mb-5">
          <div className="flex items-center gap-3">
            <Sparkles className="w-7 h-7 text-cyan-400 animate-pulse" />
            <div>
              <span className="text-[10px] font-mono uppercase text-cyan-300 tracking-wider">
                COMMUNITY CONSENSUS RATING
              </span>
              <h3 className="text-base font-bold font-mono text-white">
                {briefing.consensus_score}
              </h3>
            </div>
          </div>
        </div>

        {/* Executive Summary */}
        <div className="mb-5">
          <h4 className="text-xs font-bold font-mono text-gray-300 uppercase tracking-wider mb-2">
            Executive Research Summary
          </h4>
          <div className="p-3.5 rounded-xl bg-black/40 border border-white/5 text-xs leading-relaxed text-gray-300 font-sans">
            {briefing.executive_summary}
          </div>
        </div>

        {/* Platform Breakdown Grid */}
        <div className="mb-5">
          <h4 className="text-xs font-bold font-mono text-gray-300 uppercase tracking-wider mb-2">
            Cross-Platform Sentiment Breakdown
          </h4>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-2.5 text-xs">
            {briefing.platform_breakdown.twitter && (
              <div className="p-3 rounded-xl bg-blue-950/20 border border-blue-500/20">
                <span className="font-bold text-blue-400 block mb-1">🐦 Twitter / X</span>
                <p className="text-gray-300 text-[11px]">{briefing.platform_breakdown.twitter}</p>
              </div>
            )}
            {briefing.platform_breakdown.reddit && (
              <div className="p-3 rounded-xl bg-orange-950/20 border border-orange-500/20">
                <span className="font-bold text-orange-400 block mb-1">👽 Reddit</span>
                <p className="text-gray-300 text-[11px]">{briefing.platform_breakdown.reddit}</p>
              </div>
            )}
            {briefing.platform_breakdown.youtube && (
              <div className="p-3 rounded-xl bg-red-950/20 border border-red-500/20">
                <span className="font-bold text-red-400 block mb-1">📺 YouTube</span>
                <p className="text-gray-300 text-[11px]">{briefing.platform_breakdown.youtube}</p>
              </div>
            )}
            {briefing.platform_breakdown.web && (
              <div className="p-3 rounded-xl bg-cyan-950/20 border border-cyan-500/20">
                <span className="font-bold text-cyan-400 block mb-1">🌐 Web & News</span>
                <p className="text-gray-300 text-[11px]">{briefing.platform_breakdown.web}</p>
              </div>
            )}
          </div>
        </div>

        {/* Verified Citations */}
        {briefing.verified_citations.length > 0 && (
          <div className="mb-5">
            <h4 className="text-xs font-bold font-mono text-gray-300 uppercase tracking-wider mb-2">
              Verified Citations & Sources
            </h4>
            <div className="space-y-2 max-h-32 overflow-y-auto pr-1">
              {briefing.verified_citations.map((c, i) => {
                const badge = getPlatformBadgeStyle(c.platform);
                return (
                  <div
                    key={i}
                    className="p-2.5 rounded-lg bg-white/5 border border-white/5 flex items-start justify-between gap-2 text-xs"
                  >
                    <div>
                      <div className="flex items-center gap-1.5 mb-1">
                        <span className={`text-[9px] font-mono px-1.5 py-0.5 rounded border font-bold ${badge.bg} ${badge.border} ${badge.text}`}>
                          {c.platform}
                        </span>
                        <span className="font-bold text-gray-200">{c.author_or_source}</span>
                      </div>
                      <p className="text-gray-300 text-[11px]">&ldquo;{c.quote_or_claim}&rdquo;</p>
                    </div>
                    {c.url && (
                      <a
                        href={c.url}
                        target="_blank"
                        rel="noreferrer"
                        className="p-1 text-gray-400 hover:text-cyan-300 transition-colors flex-shrink-0"
                      >
                        <ExternalLink className="w-3.5 h-3.5" />
                      </a>
                    )}
                  </div>
                );
              })}
            </div>
          </div>
        )}

        {/* Recommended Next Steps */}
        <div className="mb-5">
          <h4 className="text-xs font-bold font-mono text-gray-300 uppercase tracking-wider mb-2">
            Recommended Actionable Next Steps
          </h4>
          <div className="space-y-1.5">
            {briefing.recommended_next_steps.map((step, i) => (
              <div key={i} className="flex items-start gap-2 text-xs text-cyan-300">
                <CheckCircle2 className="w-3.5 h-3.5 flex-shrink-0 mt-0.5" />
                <span>{step}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Webhook Dispatch Forms */}
        {dispatchType && (
          <form onSubmit={handleDispatch} className="mb-5 p-4 rounded-xl bg-cyan-950/30 border border-cyan-500/30 space-y-3">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold text-white font-mono uppercase">
                Send to {dispatchType}
              </span>
              <button
                type="button"
                onClick={() => setDispatchType(null)}
                className="text-gray-400 hover:text-white text-xs"
              >
                Cancel
              </button>
            </div>

            {dispatchType === "telegram" ? (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                <input
                  type="password"
                  placeholder="Telegram Bot Token"
                  value={telegramToken}
                  onChange={(e) => setTelegramToken(e.target.value)}
                  className="px-3 py-2 rounded-xl bg-black/60 border border-cyan-500/30 text-white text-xs font-mono"
                  required
                />
                <input
                  type="text"
                  placeholder="Chat ID (e.g. 12345678)"
                  value={telegramChatId}
                  onChange={(e) => setTelegramChatId(e.target.value)}
                  className="px-3 py-2 rounded-xl bg-black/60 border border-cyan-500/30 text-white text-xs font-mono"
                  required
                />
              </div>
            ) : (
              <input
                type="text"
                placeholder="https://hooks.slack.com/services/..."
                value={slackWebhook}
                onChange={(e) => setSlackWebhook(e.target.value)}
                className="w-full px-3 py-2 rounded-xl bg-black/60 border border-cyan-500/30 text-white text-xs font-mono"
                required
              />
            )}

            {dispatchStatus && (
              <p className="text-xs text-cyan-300 font-mono">{dispatchStatus}</p>
            )}

            <div className="flex justify-end">
              <button
                type="submit"
                disabled={isDispatching}
                className="px-4 py-1.5 rounded-xl bg-cyan-400 text-black font-bold text-xs flex items-center gap-1.5 shadow-lg shadow-cyan-500/30 font-mono"
              >
                {isDispatching ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Send className="w-3.5 h-3.5" />}
                <span>Send Now</span>
              </button>
            </div>
          </form>
        )}

        {/* Footer Actions */}
        <div className="pt-4 border-t border-cyan-500/20 flex flex-wrap items-center justify-between gap-3">
          <div className="flex items-center gap-2">
            <button
              onClick={() => setDispatchType("telegram")}
              className="px-3 py-1.5 rounded-xl bg-blue-950/40 hover:bg-blue-900/50 border border-blue-500/30 text-xs text-blue-300 flex items-center gap-1.5 transition-colors font-mono"
            >
              <Send className="w-3.5 h-3.5" />
              <span>Send to Telegram</span>
            </button>
            <button
              onClick={() => setDispatchType("slack")}
              className="px-3 py-1.5 rounded-xl bg-emerald-950/40 hover:bg-emerald-900/50 border border-emerald-500/30 text-xs text-emerald-300 flex items-center gap-1.5 transition-colors font-mono"
            >
              <MessageCircle className="w-3.5 h-3.5" />
              <span>Send to Slack</span>
            </button>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handlePrint}
              className="px-3 py-1.5 rounded-xl bg-white/5 hover:bg-white/10 border border-white/10 text-xs text-gray-300 flex items-center gap-1.5 transition-colors font-mono"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print</span>
            </button>
            <button
              onClick={handleDownloadMarkdown}
              className="px-4 py-1.5 rounded-xl bg-cyan-400 hover:bg-cyan-300 text-black font-bold text-xs flex items-center gap-1.5 transition-colors shadow-lg shadow-cyan-500/30 font-mono"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Export Markdown</span>
            </button>
          </div>
        </div>

      </div>
    </div>
  );
};
